import 'server-only';

import type { BetterAuthPlugin } from 'better-auth';
import type { GithubProfile, GoogleProfile } from 'better-auth/social-providers';

import { randomUUID } from 'crypto';

import { dash } from '@better-auth/infra';
import { passkey } from '@better-auth/passkey';
import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { nextCookies } from 'better-auth/next-js';
import {
    admin as adminPlugin,
    anonymous,
    bearer,
    emailOTP,
    haveIBeenPwned,
    jwt,
    lastLoginMethod,
    magicLink,
    multiSession,
    organization,
    twoFactor
} from 'better-auth/plugins';

import { orgAc, orgCreator, orgInstructor, orgLearner, orgManager, orgOwner } from '@/lib/auth/org-permissions';
import { ac, admin, creator, learner, staff } from '@/lib/auth/permissions';

import { env } from '@/server/config/env';
import { prismaClient } from '@/server/db/client';
import { sendMagicLinkEmail, sendOtpVerificationEmail, sendPasswordResetEmail } from '@/server/email/email-service';
import { logs } from '@/server/logging/server';

// WebAuthn relying-party config derived from the app origin. `rpID` must be the
// effective domain (hostname only, no port/scheme); `origin` is the full origin.
const appUrl = env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
const passkeyOrigin = new URL(appUrl).origin;
const passkeyRpID = new URL(appUrl).hostname;

export const auth = betterAuth({
    advanced: {
        cookiePrefix: 'better-auth',
        crossSubDomainCookies: {
            enabled: false // Disable for localhost
        },
        database: {
            // Generate IDs on the app side to satisfy Prisma create() requirements
            generateId: () => randomUUID()
        }
    },
    baseURL: env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
    cookies: {
        sessionToken: {
            httpOnly: true,
            maxAge: 60 * 60 * 24 * 7, // 7 days
            name: 'better-auth.session-token',
            sameSite: 'lax',
            secure: process.env.NODE_ENV === 'production'
        }
    },
    account: {
        accountLinking: {
            enabled: true,
            trustedProviders: ['email-password', 'github', 'google']
        }
    },
    database: prismaAdapter(prismaClient, {
        provider: 'postgresql'
    }),
    databaseHooks: {
        session: {
            create: {
                before: async session => {
                    // Reconcile role from env-based email lists on every session creation.
                    // This ensures role changes take effect on next login without manual DB updates.
                    const user = await prismaClient.user.findUnique({
                        select: { email: true, role: true },
                        where: { id: session.userId }
                    });

                    if (user?.email) {
                        const email = user.email.toLowerCase();
                        let expectedRole = 'learner';

                        if (env.ADMIN_EMAILS.includes(email)) expectedRole = 'admin';
                        else if (env.STAFF_EMAILS.includes(email)) expectedRole = 'staff';
                        else if (env.CREATOR_EMAILS.includes(email)) expectedRole = 'creator';

                        if (user.role !== expectedRole) {
                            await prismaClient.user.update({
                                data: { role: expectedRole },
                                where: { id: session.userId }
                            });
                        }
                    }

                    // Auto-assign activeOrganizationId when user has exactly one org membership
                    const memberships = await prismaClient.member.findMany({
                        select: { organizationId: true },
                        where: { userId: session.userId }
                    });

                    if (memberships.length === 1 && memberships[0]) {
                        return {
                            data: {
                                ...session,
                                activeOrganizationId: memberships[0].organizationId
                            }
                        };
                    }

                    return { data: session };
                }
            }
        },
        user: {
            create: {
                after: async user => {
                    // Fallback to "User UID#<uid>" if the name was totally missing (e.g. from GitHub)
                    if (user.firstName === 'TEMP_FIRST_NAME' || user.lastName === 'TEMP_LAST_NAME') {
                        // user.uid should now be populated since it was generated by the DB
                        const fallbackFirstName = 'User';
                        const fallbackLastName = `UID#${user.uid}`;

                        await prismaClient.user.update({
                            data: {
                                firstName: fallbackFirstName,
                                lastName: fallbackLastName
                            },
                            where: { id: user.id }
                        });
                    }
                },
                before: async user => {
                    const email = (user.email || '').toLowerCase();

                    if (env.ADMIN_EMAILS.includes(email)) {
                        return {
                            data: {
                                ...user,
                                firstName: 'Admin',
                                lastName: 'Admin',
                                role: 'admin',
                                uid: 0,
                                username: user.email.split('@')[0]
                            }
                        };
                    }

                    let role = 'learner';

                    if (env.STAFF_EMAILS.includes(email)) role = 'staff';
                    else if (env.CREATOR_EMAILS.includes(email)) role = 'creator';

                    // If name fields are still completely missing (e.g. GitHub user with no name),
                    // we'll assign a temporary marker to be replaced in the `after` hook
                    let firstName = user.firstName as string | undefined;
                    let lastName = user.lastName as string | undefined;
                    let username = user.username as string | undefined;

                    if (!firstName || firstName.trim() === '') firstName = 'TEMP_FIRST_NAME';
                    if (!lastName || lastName.trim() === '') lastName = 'TEMP_LAST_NAME';

                    if (!username) {
                        const emailStr = String(user.email || '');
                        const baseName = String(
                            firstName !== 'TEMP_FIRST_NAME' ? firstName : emailStr.split('@')[0] || ''
                        )
                            .toLowerCase()
                            .replace(/[^a-z0-9]/g, '');
                        username = `${baseName}_${randomUUID().substring(0, 6)}`;
                    }

                    return {
                        data: {
                            ...user,
                            firstName,
                            lastName,
                            role,
                            username
                        }
                    };
                }
            }
        }
    },
    emailAndPassword: {
        autoSignIn: true,
        customSyntheticUser: ({ additionalFields, coreFields, id }) => ({
            ...coreFields,
            banExpires: null,
            banned: false,
            banReason: null,
            role: 'learner',
            ...additionalFields,
            id
        }),
        enabled: true,
        requireEmailVerification: true,
        async sendResetPassword({ url, user }) {
            const params: { email: string; resetUrl: string; userName?: string } = {
                email: user.email,
                resetUrl: url
            };
            const extendedUser = user as typeof user & { firstName?: string; lastName?: string; name?: string };
            const name =
                extendedUser.name ||
                (extendedUser.firstName ? `${extendedUser.firstName} ${extendedUser.lastName}`.trim() : undefined);
            if (name) params.userName = name;

            await sendPasswordResetEmail(params);
        }
    },
    emailVerification: {
        autoSignInAfterVerification: true
    },
    plugins: [
        dash(
            env.BETTER_AUTH_API_KEY
                ? {
                      apiKey: env.BETTER_AUTH_API_KEY
                  }
                : undefined
        ) as unknown as BetterAuthPlugin,
        adminPlugin({
            ac,
            defaultRole: 'learner',
            impersonationSessionDuration: 60 * 60 * 24, // 24 hours
            roles: {
                admin,
                staff,
                creator,
                learner
            }
        }),
        organization({
            ac: orgAc,
            allowUserToCreateOrganization: true,
            requireEmailVerificationOnInvitation: true,
            roles: {
                creator: orgCreator,
                instructor: orgInstructor,
                learner: orgLearner,
                manager: orgManager,
                owner: orgOwner
            },
            schema: {
                member: {
                    modelName: 'Member'
                }
            }
        }),
        emailOTP({
            allowedAttempts: 3,
            expiresIn: 300, // 5 minutes
            otpLength: 6,
            sendVerificationOnSignUp: true,
            async sendVerificationOTP({ email, otp, type }) {
                if (process.env.NODE_ENV !== 'production') {
                    logs.auth.warn(`[DEV] OTP Verification Code for ${email}: ${otp} (Type: ${type})`);
                }
                // Only send OTP for email verification during sign up
                if (type === 'email-verification') {
                    try {
                        await sendOtpVerificationEmail({ email, otp });
                    } catch (error) {
                        if (process.env.NODE_ENV === 'production') throw error;
                        logs.auth.error(
                            '[DEV] Failed to send email via Resend, proceeding with console-only OTP.',
                            error
                        );
                    }
                }
            }
        }) as BetterAuthPlugin,
        twoFactor(),
        magicLink({
            sendMagicLink: async ({ email, url }) => {
                try {
                    await sendMagicLinkEmail({ email, url });
                } catch (error) {
                    logs.auth.error(`Failed to send magic link to ${email}`, error);
                    if (process.env.NODE_ENV !== 'production') {
                        logs.auth.warn(`[DEV FALLBACK] Magic link for ${email}: ${url}`);
                    } else {
                        throw error;
                    }
                }
            }
        }),
        passkey({
            origin: passkeyOrigin,
            rpID: passkeyRpID,
            rpName: 'Courseroad'
        }),
        haveIBeenPwned({
            customPasswordCompromisedMessage:
                'This password appeared in a public data breach. Please choose a different, more secure password.'
        }),
        lastLoginMethod({ storeInDatabase: true }),
        anonymous({
            onLinkAccount: async ({ anonymousUser, newUser }) => {
                const guestId = anonymousUser.user.id;
                const targetId = newUser.user.id;
                if (!guestId || !targetId || guestId === targetId) return;

                await prismaClient.$transaction(async tx => {
                    // Learner data without per-user uniqueness: reassign in place.
                    await tx.quizSubmission.updateMany({ data: { userId: targetId }, where: { userId: guestId } });
                    await tx.challengeSubmission.updateMany({ data: { userId: targetId }, where: { userId: guestId } });
                    await tx.deviceFingerprint.updateMany({ data: { userId: targetId }, where: { userId: guestId } });

                    // Enrollment is unique per (userId, courseId): move only rows the
                    // target does not already have; drop the guest's duplicates.
                    const targetEnrollments = await tx.enrollment.findMany({
                        select: { courseId: true },
                        where: { userId: targetId }
                    });
                    const targetCourseIds = new Set(targetEnrollments.map(e => e.courseId));
                    const guestEnrollments = await tx.enrollment.findMany({
                        select: { courseId: true, id: true },
                        where: { userId: guestId }
                    });
                    const enrollmentsToMove = guestEnrollments
                        .filter(e => !targetCourseIds.has(e.courseId))
                        .map(e => e.id);
                    const enrollmentsToDrop = guestEnrollments
                        .filter(e => targetCourseIds.has(e.courseId))
                        .map(e => e.id);
                    if (enrollmentsToMove.length > 0) {
                        await tx.enrollment.updateMany({
                            data: { userId: targetId },
                            where: { id: { in: enrollmentsToMove } }
                        });
                    }
                    if (enrollmentsToDrop.length > 0) {
                        await tx.enrollment.deleteMany({ where: { id: { in: enrollmentsToDrop } } });
                    }

                    // UserLessonProgress is unique per (userId, lessonId): same strategy.
                    const targetProgress = await tx.userLessonProgress.findMany({
                        select: { lessonId: true },
                        where: { userId: targetId }
                    });
                    const targetLessonIds = new Set(targetProgress.map(p => p.lessonId));
                    const guestProgress = await tx.userLessonProgress.findMany({
                        select: { id: true, lessonId: true },
                        where: { userId: guestId }
                    });
                    const progressToMove = guestProgress.filter(p => !targetLessonIds.has(p.lessonId)).map(p => p.id);
                    const progressToDrop = guestProgress.filter(p => targetLessonIds.has(p.lessonId)).map(p => p.id);
                    if (progressToMove.length > 0) {
                        await tx.userLessonProgress.updateMany({
                            data: { userId: targetId },
                            where: { id: { in: progressToMove } }
                        });
                    }
                    if (progressToDrop.length > 0) {
                        await tx.userLessonProgress.deleteMany({ where: { id: { in: progressToDrop } } });
                    }
                });

                logs.auth.info(`Linked anonymous user ${guestId}; migrated learner data to ${targetId}.`);
            }
        }),
        multiSession(),
        bearer(),
        jwt(),
        nextCookies()
    ],
    session: {
        cookieCache: {
            enabled: true,
            maxAge: 5 * 60 // 5 minutes
        },
        expiresIn: 60 * 60 * 24 * 7, // 7 days
        updateAge: 60 * 60 * 24 // 1 day
    },
    socialProviders: {
        github: {
            clientId: env.GITHUB_CLIENT_ID,
            clientSecret: env.GITHUB_CLIENT_SECRET,
            mapProfileToUser: (profile: GithubProfile) => {
                const fullName = profile.name || '';
                const nameParts = fullName.trim().split(' ');
                return {
                    firstName: nameParts[0] || '',
                    lastName: nameParts.slice(1).join(' ') || '',
                    name: fullName
                };
            }
        },
        google: {
            clientId: env.GOOGLE_CLIENT_ID,
            clientSecret: env.GOOGLE_CLIENT_SECRET,
            mapProfileToUser: (profile: GoogleProfile) => {
                const firstName = profile.given_name || ''; // we have to use snake_case because Google's OAuth API expects it
                const lastName = profile.family_name || ''; // we have to use snake_case because Google's OAuth API expects it
                return {
                    firstName,
                    lastName,
                    name: `${firstName} ${lastName}`.trim()
                };
            }
        }
    },
    telemetry: {
        enabled: false
    },
    trustedOrigins: [
        // Primary app URL if provided
        env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
        // Common dev hosts to ensure cookies/requests are accepted
        'http://localhost:3000',
        'http://127.0.0.1:3000'
    ],
    user: {
        additionalFields: {
            firstName: {
                required: false, // Optional to allow OAuth to trigger without it first
                type: 'string'
            },
            lastName: {
                required: false,
                type: 'string'
            },
            onboardingComplete: {
                defaultValue: false,
                type: 'boolean'
            },
            role: {
                defaultValue: 'learner',
                type: 'string'
            },
            uid: {
                required: false,
                type: 'number'
            },
            username: {
                required: false,
                type: 'string'
            }
        }
    }
});
